### ISSUE TITLE
output file is scratched --strict and variable not found

### ISSUE THREAD

**Issue by ollofx** [cykerway/jinja-cli#5]
$ echo /app/app.ini
hello {{ toto }}, I'm {{ titi }}
$ jinja2 /app/app.ini.tpl --strict -D "titi=test" -o /app/app.ini

then jinja2cli issues exception which is the expected behavior, but instead of leaving the output file as it is, it's already scratched to zero

will it be possible to only flush the output file if the jinja2cli succeeded.

this will be a bonus:
 jinja2 /app/app.ini --strict -D "titi=test" -o /app/app.ini

could the input file and the output file be the same file as

sed -i option allows to replace within the same file, so it is read processed then if everything is fine flushed back into the same file.

my aim is replace into all my scripts the sed -i by jinja2cli

Thanks a lot already for this smart package

**Comment by cykerway** [comment]
If you read the code you see the output stream is opened at the very end of the main function. So you should be able to use the same file for both input and output:

    jinja -d example.json example.j2 -o example.j2

If anything is wrong before writing the output stream, then an exception is raised, which should stop the process from running and leave the output stream untouched.

----

Finally, I wonder if you've come to the wrong place. This is `jinja-cli`. `jinja2-cli` is [here](https://github.com/mattrobenolt/jinja2-cli).

**Comment by ollofx** [comment]
indeed it is jinja2 that I'm using, I'll post this comment again there
I must admit I have not yet looked at the code, I'll make a small script reproducing the issue I have if any, and post it in the right place
