### ISSUE TITLE
Set a required variable

### ISSUE THREAD

**Issue by gotham8x** [cykerway/jinja-cli#6]
Hi thanks for a great cli.

I'm new in jinja. I have a template like this:

```conf
server {
  listen 80;
  listen [::]:80;
  server_name localhost;
  return 301 https://{{ domain }}$request_uri;
}
```

Everything works fine when I pass correct data to it `-D domain example.com`
```sh
jinja -D domain example.com  nginx.conf.tpl
```

But my teammates might miss it and cause an incorrect output, so is there any way to validate all required variables before processing further?

**Comment by cykerway** [comment]
See if `-u, --undefined` is what you want:

    jinja -u strict -D domain example.com nginx.conf.tpl
    jinja -u strict nginx.conf.tpl

It wasn't in the README. That's my bad.
