### ISSUE TITLE
Bump required Jinja2 library version to at least 2.11.0

### ISSUE THREAD

**Issue by kent007** [cykerway/jinja-cli#7]
See https://github.com/mattrobenolt/jinja2-cli/issues/94 -- I filed this with the wrong project initially, details can be found in that thread

**Comment by cykerway** [comment]
OK I saw it. Didn't expect anyone would use `Jinja2` below `2.11.0`.

I added `Jinja2` version requirement in version [1.2.1](https://github.com/cykerway/jinja-cli/tree/1.2.1). It's also the latest on PyPI now. Try upgrade and tell me how it works?

**Comment by kent007** [comment]
All working on my side.

> Didn't expect anyone would use Jinja2 below 2.11.0.

Me neither, until I had a need for a jinja CLI tool in a legacy project that was using an ancient Jinja version. At least now anyone in my shoes will get an error from `pip`!

Thanks!
