### ISSUE TITLE
chainable variable

### ISSUE THREAD

**Issue by matuskosut** [cykerway/jinja-cli#9]
Hi,

what is the expected functionality of `--undefined chainable`?

Currently it works for me same way as `--undefined ''` - undefined variables get replaced with an empty string (removed).

I would expect there to be an option where undefined values stay untouched (template.txt):
```
Example template {{ NAME }}

Config option {{ VALUE }}
```

Running a command like this: `NAME=Joe jinja -E NAME --undefined chainable template.txt`
would result in something like this:
```
Example template Joe

Config option {{ VALUE }}
```

**Comment by cykerway** [comment]
`jinja-cli` is merely a thin client. Its README has a link to Jinja's undefined variables.

For *chainable*, see https://jinja.palletsprojects.com/en/latest/api/#jinja2.ChainableUndefined

What you want is "an undefined that returns its name when printed", but I don't see where Jinja provides such a thing. Of course you can open an issue to see if they will add it.

**Comment by matuskosut** [comment]
@cykerway thanks! you are right.
